---
title: "16S draft"
author: "HP"
date: "10/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## library
```{r message=FALSE, warning=FALSE}
library(knitr)
library(tidyverse)
library(phyloseq)
library(picante)
library(Hmisc)
library(agricolae)
library(vegan)
library(ape)
library(usedist)
library(grid)
library(gridExtra)
library(gtable)
library(ggpubr)
library(ggrepel)
library(qiime2R)
```

## data preparation
### set colors, labs and so on
```{r}
col_facility = c("#252525", "#1b9e77")
names(col_facility) = c("Vivarium", "Farm")
col_treatment = c("#Ad61c6", "darkgreen")
names(col_treatment) = c("Chlorinated", "Diwater")
col_sex = c("#F1726D", "#2b8cbe")
names(col_sex) <- c("Female", "Male")
col_age = c("#F9966D", "#Da87e7", "navy")
names(col_age) = c("Week 3","Week 7","Week 12")

labs_sex <- c("Female", "Male")
names(labs_sex) <- c("F", "M")
labs_facility <- c("Vivarium", "Farm")
names(labs_facility) <- c("Vivarium", "Farm")
labs_treatment <- c("Chlorinated", "Diwater")
names(labs_treatment) <- c("Chlorinated", "Diwater")
col_timepoint_pup = c("#f1eef6", "#d0d1e6", "#a6bddb", "#74a9cf", "#2b8cbe", "#045a8d")
names(col_timepoint_pup) = c("Week3","Week4","Week5","Week7","Week9","Week12")
col_timepoint_mom = c("#bdc9e1",  "#74a9cf", "#0570b0")
names(col_timepoint_mom) = c("E16", "Weaning", "End")

```

### diversity
```{r}
a1 = qiime2R::read_qza("/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/07_diversity/core-metrics-results_10000/faith_pd_vector.qza")
a2 = qiime2R::read_qza("/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/07_diversity/core-metrics-results_10000/observed_features_vector.qza")
a3 = qiime2R::read_qza("/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/07_diversity/core-metrics-results_10000/evenness_vector.qza")
a4 = qiime2R::read_qza("/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/07_diversity/core-metrics-results_10000/shannon_vector.qza")

alpha = cbind(a1$data, a2$data, a3$data, a4$data) %>% rownames_to_column(var = "SampleID")
names(alpha) = c("SampleID","faith_pd","observed_ASVs","pielou_evenness","shannon_index")

a = qiime2R::read_qza("/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/07_diversity/core-metrics-results_10000/bray_curtis_distance_matrix.qza")
dm_bray = a$data
a = qiime2R::read_qza("/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/07_diversity/core-metrics-results_10000/jaccard_distance_matrix.qza")
dm_jaccard = a$data
a = qiime2R::read_qza("/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/07_diversity/core-metrics-results_10000/unweighted_unifrac_distance_matrix.qza")
dm_uufrac = a$data
a = qiime2R::read_qza("/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/07_diversity/core-metrics-results_10000/weighted_unifrac_distance_matrix.qza")
dm_wufrac = a$data
rm(a1, a2, a3, a4, a)
```

### phylo object
```{r}
library(phyloseq)
phylo_all =  qiime2R::qza_to_phyloseq(features = "/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/05_merged/table_all.qza",
                             taxonomy = "/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/06_taxa/taxonomy_dada_silva138.qza",
                             tree =  "/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/05_merged/rooted_tree.qza",
                             metadata = "/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/Mapping_Chlorination2019_20191111-merged-JW.txt")

phylo_rf =  qiime2R::qza_to_phyloseq(features = "/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/07_diversity/core-metrics-results_10000/rarefied_table.qza",
                             taxonomy = "/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/06_taxa/taxonomy_dada_silva138.qza",
                             tree =  "/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/05_merged/rooted_tree.qza",
                             metadata = "/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/Mapping_Chlorination2019_20191111-merged-JW.txt")

meta = phylo_all@sam_data@.Data %>% as.data.frame()
names(meta) = phylo_all@sam_data@names
meta$SampleID = phylo_all@sam_data@row.names
meta$Seq_count = sample_sums(phylo_all)
#correct dates
meta = meta %>% mutate(DOB = lubridate::mdy(DOB))
a1 = meta %>% filter(str_detect(SamplingDate, "/19")) %>% mutate(SamplingDate = lubridate::mdy(SamplingDate))
a2 = meta %>% filter(str_detect(SamplingDate, "2019")) %>% 
  mutate(SamplingDate = lubridate::mdy(paste(str_sub(SamplingDate,1,1),str_sub(SamplingDate,2,3),str_sub(SamplingDate,4,7),sep = "-")))
a3 = meta %>% filter(is.na(SamplingDate))
meta_16S = rbind(a1, a2, a3)
meta_16S$SamplingTimepoint =  str_remove(meta_16S$SamplingTimepoint, " $")
#correct facility
meta_16S = meta_16S %>% mutate(f_temp = ifelse(str_detect(SubjectID, "^F"), "Farm", "Bartlett")) %>% 
  arrange(SampleID) %>% 
  mutate(check = str_c(SampleID,SubjectID, SamplingTimepoint, f_temp, TREATMENT, Sex, sep = ";"))

meta2 = readxl::read_excel("/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/Mapping_Chlorination2019_20191111_merged_JW_final.xlsx")
meta2 = meta2 %>% arrange(SampleID) %>%  mutate(check = str_c(SampleID,SubjectID,SamplingTimepoint,Facility,TREATMENT,Sex, sep=";"))
#make sure all information are correct
sum((meta2 %>% filter(Body_Site == "Feces") %>% pull(check)) == (meta_16S %>% filter(Body_Site == "Feces") %>% pull(check)))
length(meta2 %>% filter(Body_Site == "Feces") %>% pull(check))
meta_16S =  meta_16S %>% mutate(Facility = f_temp) %>% select(-c(f_temp, check))
#merge week 11, 12 for moms
meta_16S =  meta_16S %>% mutate(SamplingTimepoint_mom = case_when(SamplingTimepoint == "E16" ~ "E16",
                                                                  (SamplingTimepoint == "Week3" & Generation == "F0") ~ "Weaning",
                                                                  SamplingTimepoint == "Week11" ~ "End",
                                                                  (SamplingTimepoint == "Week12" & Generation == "F0") ~ "End",
                                                                  TRUE ~ NA_character_)) %>%
  mutate(SamplingTimepoint_mom = factor(SamplingTimepoint_mom, levels = c("E16", "Weaning", "End"), ordered = T))

a = sample_data(meta_16S %>% column_to_rownames(var = "SampleID"))
sample_data(phylo_all) = a
sample_data(phylo_rf) = a
rm(meta, a, a1, a2, a3)
write.table(meta_16S, file = "/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/meta_final.txt", sep = "\t", quote = FALSE, row.names = FALSE)
```

### taxa anno
```{r}
taxa = tax_table(phylo_all@tax_table) %>% as.matrix() %>% as.data.frame() %>% rownames_to_column(var = "id")
taxa = taxa %>% mutate(ASV = str_c("asv_", 1:nrow(taxa)),
                       Kingdom = str_replace_na(Kingdom,"k_"),
                       Kingdom = str_replace(Kingdom, "d__", ""),
                       Phylum = str_replace_na(Phylum,"p_"),
                       Class = str_replace_na(Class,"c_"),
                       Order = str_replace_na(Order,"o_"),
                       Family = str_replace_na(Family,"f_"),
                       Genus = str_replace_na(Genus,"g_"),
                       Species = str_replace_na(Species,"s_")
                      )
```

### save all variables for quick access
```{r}
save.image(file = "temp.RData")
```

### export
```{r}
load("temp.RData")

ft <- phylo_rf@otu_table@.Data

wmeta <- meta_16S %>% 
  filter(TREATMENT == "DIWATER", Generation == "F1", SamplingTimepoint %in% c("Week3","Week12")) %>% 
  transmute(SampleID, FamilyID, SubjectID, Sex,  Facility, SamplingTimepoint)

ft <- ft[,wmeta$SampleID]
ft <- ft[rowSums(ft)>0,]
ft <- ft %>% as.data.frame() %>% 
  rownames_to_column(var = "ASV")

write.table(wmeta, file = "/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/Chlorination_metadata.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
write.table(ft, file = "/Users/aiswaryaa/Downloads/CL_rna/20211015_CL_analysis_new/Chlorination_table.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
```


